/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.assignmentcode;

import EligibilityCheckandEnrolment.EnrolStudentForRecovery;

public class Enrol_Student_for_Recovery extends javax.swing.JFrame {

    private EnrolStudentForRecovery logic;

    public Enrol_Student_for_Recovery() {
        initComponents();
        logic = new EnrolStudentForRecovery();
        // The logic class now handles refreshing the table initially too
        logic.refreshTable(eligibility_Tlb);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        StdID_txt = new javax.swing.JTextField();
        Course_txt = new javax.swing.JTextField();
        UtdGrd_btn = new javax.swing.JButton();
        SendEm_btn = new javax.swing.JButton();
        Del_btn = new javax.swing.JButton();
        Add_btn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        eligibility_Tlb = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ExamMk_txt = new javax.swing.JTextField();
        AssmMk_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        StdNm_txt1 = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Enrol Eligibility");

        jLabel3.setText("Student ID");

        jLabel4.setText("Course ID");

        UtdGrd_btn.setText("Update Grade");
        UtdGrd_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UtdGrd_btnActionPerformed(evt);
            }
        });

        SendEm_btn.setText("Send Email");
        SendEm_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendEm_btnActionPerformed(evt);
            }
        });

        Del_btn.setText("Delete");
        Del_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Del_btnActionPerformed(evt);
            }
        });

        Add_btn.setText("Add Grade");
        Add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_btnActionPerformed(evt);
            }
        });

        eligibility_Tlb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Student Name", "Student ID", "Course", "Exam Mark", "Assignment Mark", "Final Grade", "Grade Point"
            }
        ));
        jScrollPane2.setViewportView(eligibility_Tlb);

        jLabel6.setText("Exam Mark");

        jLabel7.setText("Assignmnet Mark");

        ExamMk_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExamMk_txtActionPerformed(evt);
            }
        });

        AssmMk_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssmMk_txtActionPerformed(evt);
            }
        });

        jLabel5.setText("Student Name");

        StdNm_txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StdNm_txt1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(Add_btn)
                        .addGap(76, 76, 76)
                        .addComponent(Del_btn)
                        .addGap(71, 71, 71)
                        .addComponent(UtdGrd_btn)
                        .addGap(75, 75, 75)
                        .addComponent(SendEm_btn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 906, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel5)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ExamMk_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Course_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(StdNm_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(124, 124, 124)
                                .addComponent(jLabel7)
                                .addGap(28, 28, 28)
                                .addComponent(AssmMk_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(StdID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(363, 363, 363)
                        .addComponent(jLabel1)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AssmMk_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(StdNm_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StdID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Course_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ExamMk_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add_btn)
                    .addComponent(Del_btn)
                    .addComponent(UtdGrd_btn)
                    .addComponent(SendEm_btn))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UtdGrd_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UtdGrd_btnActionPerformed
       logic.updateGrade(this, eligibility_Tlb, StdID_txt, Course_txt, ExamMk_txt, AssmMk_txt);
    }//GEN-LAST:event_UtdGrd_btnActionPerformed

    private void SendEm_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendEm_btnActionPerformed
       logic.sendRecoveryEmail(this, eligibility_Tlb);
    }//GEN-LAST:event_SendEm_btnActionPerformed

    private void Del_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Del_btnActionPerformed
        logic.deleteGrade(this, eligibility_Tlb, StdID_txt, Course_txt);
    }//GEN-LAST:event_Del_btnActionPerformed

    private void Add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_btnActionPerformed
        // ONE LINE call. Logic handles extraction, validation, saving, refreshing, and clearing fields.
        logic.addGrade(this, eligibility_Tlb, StdNm_txt1, StdID_txt, Course_txt, ExamMk_txt, AssmMk_txt);
    }//GEN-LAST:event_Add_btnActionPerformed

    private void ExamMk_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExamMk_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExamMk_txtActionPerformed

    private void AssmMk_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssmMk_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AssmMk_txtActionPerformed

    private void StdNm_txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StdNm_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StdNm_txt1ActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(Enrol_Student_for_Recovery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Enrol_Student_for_Recovery().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_btn;
    private javax.swing.JTextField AssmMk_txt;
    private javax.swing.JTextField Course_txt;
    private javax.swing.JButton Del_btn;
    private javax.swing.JTextField ExamMk_txt;
    private javax.swing.JButton SendEm_btn;
    private javax.swing.JTextField StdID_txt;
    private javax.swing.JTextField StdNm_txt1;
    private javax.swing.JButton UtdGrd_btn;
    private javax.swing.JTable eligibility_Tlb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
