/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.assignmentcode;

/**
 *
 * @author William
 */

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;

public class PlanRecommendationForm extends javax.swing.JFrame {

    PlanRecommendationManager manager = new PlanRecommendationManager();
    StudentValidationManager validator = new StudentValidationManager();
    String filename = "CourseRecoveryPlan.txt";
    /**
     * Creates new form PlanRecommendationForm
     */
    public PlanRecommendationForm() {
        initComponents();
        displayRecommendations();
        
        examRBTN.addActionListener(e -> ComponentTXT.setText("Exam"));
        assignmentRBTN.addActionListener(e -> ComponentTXT.setText("Assignment"));
        ComponentTXT.setEditable(false);
        
        recoveryPlanTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableRowClicked(evt);
            }
        });
    }
    
    private void displayRecommendations() {
        DefaultTableModel model = (DefaultTableModel) recoveryPlanTable.getModel();
        model.setRowCount(0); // Clear existing rows

        List<PlanRecommendation> recommendations = manager.loadFromFile(filename);
        for (PlanRecommendation rec : recommendations) {
            model.addRow(new Object[]{
                rec.getStudentID(),
                rec.getCourseID(),
                rec.getComponent(),
                rec.getRecommendation()
            });
        }
    }
    
    private void tableRowClicked(java.awt.event.MouseEvent evt) {
        int selectedRow = recoveryPlanTable.getSelectedRow();
        if (selectedRow >= 0) {
            // Get table values
            String studentID = recoveryPlanTable.getValueAt(selectedRow, 0).toString();
            String courseID = recoveryPlanTable.getValueAt(selectedRow, 1).toString();
            String component = recoveryPlanTable.getValueAt(selectedRow, 2).toString();
            String recommendation = recoveryPlanTable.getValueAt(selectedRow, 3).toString();

            // Fill text fields
            StudentIDTXT.setText(studentID);
            CourseIDTXT.setText(courseID);
            ComponentTXT.setText(component);
            RecommendationTXT.setText(recommendation);
        }
    }
    
    private void clearFields() {
        StudentIDTXT.setText("");
        CourseIDTXT.setText("");
        ComponentTXT.setText("");
        RecommendationTXT.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        failedComponentTable = new javax.swing.JTable();
        jToggleButton1 = new javax.swing.JToggleButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        recoveryPlanTable = new javax.swing.JTable();
        addPlanBTN = new javax.swing.JButton();
        updatePlanBTN = new javax.swing.JButton();
        removePlanBTN = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        StudentIDTXT = new javax.swing.JTextField();
        CourseIDTXT = new javax.swing.JTextField();
        RecommendationTXT = new javax.swing.JTextField();
        searchPlanBTN = new javax.swing.JButton();
        resetPlanBTN = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        ComponentTXT = new javax.swing.JTextField();
        examRBTN = new javax.swing.JRadioButton();
        assignmentRBTN = new javax.swing.JRadioButton();

        failedComponentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "StudentID", "CourseID", "Component", "Mark", "Final Grade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(failedComponentTable);

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Recovery Plan");

        recoveryPlanTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "StudentID", "CourseID", "Component", "Recommendation"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(recoveryPlanTable);

        addPlanBTN.setText("Add");
        addPlanBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPlanBTNActionPerformed(evt);
            }
        });

        updatePlanBTN.setText("Update");
        updatePlanBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePlanBTNActionPerformed(evt);
            }
        });

        removePlanBTN.setText("Remove");
        removePlanBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removePlanBTNActionPerformed(evt);
            }
        });

        jLabel2.setText("Student ID:");

        jLabel3.setText("Course ID:");

        jLabel4.setText("Component:");

        StudentIDTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentIDTXTActionPerformed(evt);
            }
        });

        searchPlanBTN.setText("Search");
        searchPlanBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPlanBTNActionPerformed(evt);
            }
        });

        resetPlanBTN.setText("Reset");
        resetPlanBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetPlanBTNActionPerformed(evt);
            }
        });

        jLabel6.setText("Recommendation:");

        buttonGroup1.add(examRBTN);
        examRBTN.setText("Exam");

        buttonGroup1.add(assignmentRBTN);
        assignmentRBTN.setText("Assignment");
        assignmentRBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignmentRBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(260, 260, 260))))
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(addPlanBTN)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(updatePlanBTN)
                        .addGap(80, 80, 80)
                        .addComponent(removePlanBTN)
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resetPlanBTN)
                            .addComponent(searchPlanBTN)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RecommendationTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(StudentIDTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(CourseIDTXT)
                            .addComponent(ComponentTXT))
                        .addGap(18, 18, 18)
                        .addComponent(examRBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(assignmentRBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(StudentIDTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(resetPlanBTN)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(CourseIDTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ComponentTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(examRBTN)
                                .addComponent(assignmentRBTN)))
                        .addGap(29, 29, 29))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RecommendationTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatePlanBTN)
                    .addComponent(addPlanBTN)
                    .addComponent(removePlanBTN)
                    .addComponent(searchPlanBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updatePlanBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePlanBTNActionPerformed
        int selectedRow = recoveryPlanTable.getSelectedRow();
        
        if (selectedRow >= 0) {    
            String studentID = StudentIDTXT.getText();
            String courseID = CourseIDTXT.getText();
            String component = ComponentTXT.getText();
            String recText = RecommendationTXT.getText();
        
            if (studentID.isEmpty() || courseID.isEmpty() || component.isEmpty() || recText.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please fill in all fields!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (!validator.isValidStudent(studentID)) {
                JOptionPane.showMessageDialog(this, "Invalid Student ID! Please enter an existing student.");
                return;
            }

            if (!validator.isValidCourse(courseID)) {
                JOptionPane.showMessageDialog(this, "Invalid Course ID! Please enter an existing course.");
                return;
            }
                
            int confirm = JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to update this recommendation?",
                "Confirm Update",
                JOptionPane.YES_NO_OPTION
            );

            if (confirm == JOptionPane.YES_OPTION) {
                manager.updateRecord(filename, StudentIDTXT.getText(), CourseIDTXT.getText(), ComponentTXT.getText(), RecommendationTXT.getText());
                JOptionPane.showMessageDialog(this, "Recommendation updated successfully!");
                displayRecommendations();
                clearFields();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a row to update.");
        }
            
    }//GEN-LAST:event_updatePlanBTNActionPerformed

    private void addPlanBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPlanBTNActionPerformed
        String studentID = StudentIDTXT.getText();
        String courseID = CourseIDTXT.getText();
        String component = ComponentTXT.getText();
        String recText = RecommendationTXT.getText();
        
        if (studentID.isEmpty() || courseID.isEmpty() || component.isEmpty() || recText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!validator.isValidStudent(studentID)) {
            JOptionPane.showMessageDialog(this, "Invalid Student ID! Please enter an existing student.");
            return;
        }
        
        if (!validator.isValidCourse(courseID)) {
            JOptionPane.showMessageDialog(this, "Invalid Course ID! Please enter an existing course.");
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to add this new recommendation?",
            "Confirm Add",
            JOptionPane.YES_NO_OPTION
        );


        if (confirm == JOptionPane.YES_OPTION) {
            PlanRecommendation newRec = new PlanRecommendation(studentID, courseID, component, recText);
            manager.addRecord(filename, newRec);
            JOptionPane.showMessageDialog(this, "Recommendation added successfully!");
            displayRecommendations();
            clearFields();
        }

        //Clear input fields
        StudentIDTXT.setText("");
        CourseIDTXT.setText("");
        ComponentTXT.setText("");
        RecommendationTXT.setText("");
    }//GEN-LAST:event_addPlanBTNActionPerformed

    private void StudentIDTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentIDTXTActionPerformed
        
    }//GEN-LAST:event_StudentIDTXTActionPerformed

    private void removePlanBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removePlanBTNActionPerformed
        int selectedRow = recoveryPlanTable.getSelectedRow();
        
        if (selectedRow >= 0) {
            // Get values from the selected row
            String studentID = recoveryPlanTable.getValueAt(selectedRow, 0).toString();
            String courseID = recoveryPlanTable.getValueAt(selectedRow, 1).toString();
            

            // Confirm deletion
            int confirm = JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to remove the recommendation for Student ID: " + studentID + 
                " and Course ID: " + courseID + "?",
                "Confirm Deletion",
                JOptionPane.YES_NO_OPTION
            );
            
            if (confirm == JOptionPane.YES_OPTION) {
                // Remove from file
                manager.removeRecord(filename, studentID, courseID);
                JOptionPane.showMessageDialog(this, "Recommendation removed successfully!");

                // Refresh table and clear text fields
                displayRecommendations();
                clearFields();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a row to remove.");
        }   
    }//GEN-LAST:event_removePlanBTNActionPerformed

    private void searchPlanBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPlanBTNActionPerformed
        String studentID = StudentIDTXT.getText();
        String courseID = CourseIDTXT.getText();
        String component = ComponentTXT.getText();
        String recommendation = RecommendationTXT.getText();
    
        List<PlanRecommendation> results = manager.searchRecord(studentID, courseID, component, recommendation);   
        
        DefaultTableModel model = (DefaultTableModel) recoveryPlanTable.getModel();
        model.setRowCount(0);
        
        for (PlanRecommendation rec : results) {
            model.addRow(new Object[] {
                rec.getStudentID(),
                rec.getCourseID(),
                rec.getComponent(),
                rec.getRecommendation()
            });
        }
        
        if (results.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No matching records found.");
        }
    }//GEN-LAST:event_searchPlanBTNActionPerformed

    private void resetPlanBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetPlanBTNActionPerformed
        List<PlanRecommendation> allRecs = manager.loadFromFile(filename);

        DefaultTableModel model = (DefaultTableModel) recoveryPlanTable.getModel();
        model.setRowCount(0);

        for (PlanRecommendation rec : allRecs) {
            model.addRow(new Object[]{
                rec.getStudentID(),
                rec.getCourseID(),
                rec.getComponent(),
                rec.getRecommendation()
            });
        }
        
        StudentIDTXT.setText("");
        CourseIDTXT.setText("");
        ComponentTXT.setText("");
        RecommendationTXT.setText("");
    }//GEN-LAST:event_resetPlanBTNActionPerformed

    private void assignmentRBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignmentRBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assignmentRBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlanRecommendationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlanRecommendationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlanRecommendationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlanRecommendationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlanRecommendationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ComponentTXT;
    private javax.swing.JTextField CourseIDTXT;
    private javax.swing.JTextField RecommendationTXT;
    private javax.swing.JTextField StudentIDTXT;
    private javax.swing.JButton addPlanBTN;
    private javax.swing.JRadioButton assignmentRBTN;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton examRBTN;
    private javax.swing.JTable failedComponentTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTable recoveryPlanTable;
    private javax.swing.JButton removePlanBTN;
    private javax.swing.JButton resetPlanBTN;
    private javax.swing.JButton searchPlanBTN;
    private javax.swing.JButton updatePlanBTN;
    // End of variables declaration//GEN-END:variables
}
