/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.assignmentcode;

import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author William
 */
public class RecoveryMilestoneForm extends javax.swing.JFrame {
    
    RecoveryMilestoneManager manager = new RecoveryMilestoneManager();
    StudentValidationManager validator = new StudentValidationManager();
    String filename = "RecoveryMilestone.txt";
    /**
     * Creates new form NewJFrame
     */
    public RecoveryMilestoneForm() {
        initComponents();
        displayMilestone();
        
        milestoneTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableRowClicked(evt);
            }
        });
    }
    
    private void displayMilestone() {
        DefaultTableModel model = (DefaultTableModel) milestoneTable.getModel();
        model.setRowCount(0); // Clear existing rows

        List<RecoveryMilestone> milestones = manager.loadFromFile(filename);
        for (RecoveryMilestone rec : milestones) {
            model.addRow(new Object[]{
                rec.getStudentID(),
                rec.getCourseID(),
                rec.getWeek(),
                rec.getTask()
            });
        }
    }
    
    private void tableRowClicked(java.awt.event.MouseEvent evt) {
        int selectedRow = milestoneTable.getSelectedRow();
        if (selectedRow >= 0) {
            // Get table values
            String studentID = milestoneTable.getValueAt(selectedRow, 0).toString();
            String courseID = milestoneTable.getValueAt(selectedRow, 1).toString();
            String week = milestoneTable.getValueAt(selectedRow, 2).toString();
            String task = milestoneTable.getValueAt(selectedRow, 3).toString();

            // Fill text fields
            StudentIDTXT.setText(studentID);
            CourseIDTXT.setText(courseID);
            WeekTXT.setText(week);
            TaskTXT.setText(task);
        }
    }
    
    private void clearFields() {
        StudentIDTXT.setText("");
        CourseIDTXT.setText("");
        WeekTXT.setText("");
        TaskTXT.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        StudentIDTXT = new javax.swing.JTextField();
        CourseIDTXT = new javax.swing.JTextField();
        addMilestoneBTN = new javax.swing.JButton();
        updateMilestoneBTN = new javax.swing.JButton();
        removeMilestoneBTN = new javax.swing.JButton();
        searchMilestoneBTN = new javax.swing.JButton();
        resetMilestoneBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        milestoneTable = new javax.swing.JTable();
        WeekTXT = new javax.swing.JTextField();
        TaskTXT = new javax.swing.JTextField();
        emailBTN = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Recovery Plan");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Recovery Milestone");

        jLabel3.setText("Student ID:");

        jLabel4.setText("Course ID:");

        jLabel5.setText("Week:");

        jLabel6.setText("Task:");

        addMilestoneBTN.setText("Add");
        addMilestoneBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMilestoneBTNActionPerformed(evt);
            }
        });

        updateMilestoneBTN.setText("Update");
        updateMilestoneBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateMilestoneBTNActionPerformed(evt);
            }
        });

        removeMilestoneBTN.setText("Remove");
        removeMilestoneBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeMilestoneBTNActionPerformed(evt);
            }
        });

        searchMilestoneBTN.setText("Search");
        searchMilestoneBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchMilestoneBTNActionPerformed(evt);
            }
        });

        resetMilestoneBTN.setText("Reset");
        resetMilestoneBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetMilestoneBTNActionPerformed(evt);
            }
        });

        milestoneTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Student ID", "Course ID", "Week", "Task"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(milestoneTable);

        emailBTN.setText("Email");
        emailBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(224, 224, 224))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(StudentIDTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(331, 331, 331))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(addMilestoneBTN)
                                        .addGap(71, 71, 71)
                                        .addComponent(updateMilestoneBTN)
                                        .addGap(70, 70, 70)
                                        .addComponent(removeMilestoneBTN)
                                        .addGap(72, 72, 72))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(119, 119, 119)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel6))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CourseIDTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(WeekTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TaskTXT))
                                        .addGap(68, 68, 68)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(resetMilestoneBTN)
                                    .addComponent(searchMilestoneBTN)
                                    .addComponent(emailBTN))
                                .addGap(55, 55, 55)))
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(StudentIDTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CourseIDTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(resetMilestoneBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(WeekTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TaskTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addMilestoneBTN)
                    .addComponent(updateMilestoneBTN)
                    .addComponent(removeMilestoneBTN)
                    .addComponent(searchMilestoneBTN))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addMilestoneBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMilestoneBTNActionPerformed
        String studentID = StudentIDTXT.getText();
        String courseID = CourseIDTXT.getText();
        String week = WeekTXT.getText();
        String task = TaskTXT.getText();
        
        if (studentID.isEmpty() || courseID.isEmpty() || week.isEmpty() || task.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!validator.isValidStudent(studentID)) {
            JOptionPane.showMessageDialog(this, "Invalid Student ID! Please enter an existing student.");
            return;
        }
        
        if (!validator.isValidCourse(courseID)) {
            JOptionPane.showMessageDialog(this, "Invalid Course ID! Please enter an existing course.");
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to add this new Milestone?",
            "Confirm Add",
            JOptionPane.YES_NO_OPTION
        );


        if (confirm == JOptionPane.YES_OPTION) {
            RecoveryMilestone newRec = new RecoveryMilestone(studentID, courseID, week, task);            
            manager.addRecord(filename, newRec);
            JOptionPane.showMessageDialog(this, "Milestone added successfully!");
            displayMilestone();
            clearFields();
        }

        //Clear input fields
        StudentIDTXT.setText("");
        CourseIDTXT.setText("");
        WeekTXT.setText("");
        TaskTXT.setText("");
    }//GEN-LAST:event_addMilestoneBTNActionPerformed

    private void updateMilestoneBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateMilestoneBTNActionPerformed
        int selectedRow = milestoneTable.getSelectedRow();
        
        if (selectedRow >= 0) {    
            String studentID = StudentIDTXT.getText();
            String courseID = CourseIDTXT.getText();
            String week = WeekTXT.getText();
            String task = TaskTXT.getText();
        
            if (studentID.isEmpty() || courseID.isEmpty() || week.isEmpty() || task.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please fill in all fields!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (!validator.isValidStudent(studentID)) {
                JOptionPane.showMessageDialog(this, "Invalid Student ID! Please enter an existing student.");
                return;
            }

            if (!validator.isValidCourse(courseID)) {
                JOptionPane.showMessageDialog(this, "Invalid Course ID! Please enter an existing course.");
                return;
            }
                
            int confirm = JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to update this Milestone?",
                "Confirm Update",
                JOptionPane.YES_NO_OPTION
            );

            if (confirm == JOptionPane.YES_OPTION) {
                manager.setTargetIndex(selectedRow);
                manager.updateRecord(filename, StudentIDTXT.getText(), CourseIDTXT.getText(), WeekTXT.getText(), TaskTXT.getText());
                JOptionPane.showMessageDialog(this, "Milestone updated successfully!");
                displayMilestone();
                clearFields();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a row to update.");
        }
    }//GEN-LAST:event_updateMilestoneBTNActionPerformed

    private void removeMilestoneBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeMilestoneBTNActionPerformed
        int selectedRow = milestoneTable.getSelectedRow();
        
        if (selectedRow >= 0) {
            // Get values from the selected row
            String studentID = milestoneTable.getValueAt(selectedRow, 0).toString();
            String courseID = milestoneTable.getValueAt(selectedRow, 1).toString();
            

            // Confirm deletion
            int confirm = JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to remove the milestone for Student ID: " + studentID + 
                " and Course ID: " + courseID + "?",
                "Confirm Deletion",
                JOptionPane.YES_NO_OPTION
            );
            
            if (confirm == JOptionPane.YES_OPTION) {
                // Remove from file
                manager.removeRecord(filename, studentID, courseID);
                JOptionPane.showMessageDialog(this, "Milestone removed successfully!");

                // Refresh table and clear text fields
                displayMilestone();
                clearFields();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a row to remove.");
        }   
    }//GEN-LAST:event_removeMilestoneBTNActionPerformed

    private void searchMilestoneBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchMilestoneBTNActionPerformed
        String studentID = StudentIDTXT.getText();
        String courseID = CourseIDTXT.getText();
        String week = WeekTXT.getText();
        String task = TaskTXT.getText();
    
        List<RecoveryMilestone> results = manager.searchRecord(studentID, courseID, week, task);   
        
        DefaultTableModel model = (DefaultTableModel) milestoneTable.getModel();
        model.setRowCount(0);
        
        for (RecoveryMilestone rec : results) {
            model.addRow(new Object[] {
                rec.getStudentID(),
                rec.getCourseID(),
                rec.getWeek(),
                rec.getTask()
            });
        }
        
        if (results.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No matching records found.");
        }
    }//GEN-LAST:event_searchMilestoneBTNActionPerformed

    private void resetMilestoneBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetMilestoneBTNActionPerformed
        List<RecoveryMilestone> allRecs = manager.loadFromFile(filename);

        DefaultTableModel model = (DefaultTableModel) milestoneTable.getModel();
        model.setRowCount(0);

        for (RecoveryMilestone rec : allRecs) {
            model.addRow(new Object[]{
                rec.getStudentID(),
                rec.getCourseID(),
                rec.getWeek(),
                rec.getTask()
            });
        }
        
        StudentIDTXT.setText("");
        CourseIDTXT.setText("");
        WeekTXT.setText("");
        TaskTXT.setText("");
    }//GEN-LAST:event_resetMilestoneBTNActionPerformed

    private void emailBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailBTNActionPerformed
        int[] selectedRows = milestoneTable.getSelectedRows();
        if (selectedRows.length == 0) {
            JOptionPane.showMessageDialog(this, "Please select at least one milestone to send.");
            return;
        }

        List<RecoveryMilestone> selectedMilestones = new ArrayList<>();
        for (int row : selectedRows) {
            String studentID = milestoneTable.getValueAt(row, 0).toString();
            String courseID = milestoneTable.getValueAt(row, 1).toString();
            String week = milestoneTable.getValueAt(row, 2).toString();
            String task = milestoneTable.getValueAt(row, 3).toString();

            selectedMilestones.add(new RecoveryMilestone(studentID, courseID, week, task));
        }

        manager.sendEmailNoti(selectedMilestones);
        JOptionPane.showMessageDialog(this, "Emails sent successfully!");
    }//GEN-LAST:event_emailBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecoveryMilestoneForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecoveryMilestoneForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecoveryMilestoneForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecoveryMilestoneForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecoveryMilestoneForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CourseIDTXT;
    private javax.swing.JTextField StudentIDTXT;
    private javax.swing.JTextField TaskTXT;
    private javax.swing.JTextField WeekTXT;
    private javax.swing.JButton addMilestoneBTN;
    private javax.swing.JButton emailBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable milestoneTable;
    private javax.swing.JButton removeMilestoneBTN;
    private javax.swing.JButton resetMilestoneBTN;
    private javax.swing.JButton searchMilestoneBTN;
    private javax.swing.JButton updateMilestoneBTN;
    // End of variables declaration//GEN-END:variables
}
