/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.assignmentcode;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author William
 */
public class RecoveryProgressForm extends javax.swing.JFrame {
    
    RecoveryProgressManager manager = new RecoveryProgressManager();
    StudentValidationManager validator = new StudentValidationManager();
    String filename = "RecoveryProgress.txt";
    /**
     * Creates new form RecoveryProgressForm
     */
    public RecoveryProgressForm() {
        initComponents();
        displayProgress();
        
        examRBTN.addActionListener(e -> ComponentTXT.setText("Exam"));
        assignmentRBTN.addActionListener(e -> ComponentTXT.setText("Assignment"));
        ComponentTXT.setEditable(false);
        
        pendingRBTN.addActionListener(e -> ProgressTXT.setText("Pending"));
        inProgRBTN.addActionListener(e -> ProgressTXT.setText("In Progress"));
        completedRBTN.addActionListener(e -> ProgressTXT.setText("Completed"));
        ProgressTXT.setEditable(false);
        
        progressTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableRowClicked(evt);
            }
        });
    }
    
    private void displayProgress() {
        DefaultTableModel model = (DefaultTableModel) progressTable.getModel();
        model.setRowCount(0); // Clear existing rows

        List<RecoveryProgress> progresses = manager.loadFromFile(filename);
        for (RecoveryProgress rec : progresses) {
            model.addRow(new Object[]{
                rec.getStudentID(),
                rec.getCourseID(),
                rec.getComponent(),
                rec.getProgress(),
                rec.getRecoveryMark()
            });
        }
    }
    
    private void tableRowClicked(java.awt.event.MouseEvent evt) {
        int selectedRow = progressTable.getSelectedRow();
        if (selectedRow >= 0) {
            // Get table values
            String studentID = progressTable.getValueAt(selectedRow, 0).toString();
            String courseID = progressTable.getValueAt(selectedRow, 1).toString();
            String component = progressTable.getValueAt(selectedRow, 2).toString();
            String progress = progressTable.getValueAt(selectedRow, 3).toString();
            String recMark = progressTable.getValueAt(selectedRow, 4).toString();

            // Fill text fields
            StudentIDTXT.setText(studentID);
            CourseIDTXT.setText(courseID);
            ComponentTXT.setText(component);
            ProgressTXT.setText(progress);
            RecMarkTXT.setText(recMark);
        }
    }
    
    private void clearFields() {
        StudentIDTXT.setText("");
        CourseIDTXT.setText("");
        ComponentTXT.setText("");
        ProgressTXT.setText("");
        RecMarkTXT.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        ProgressTXT = new javax.swing.JTextField();
        resetProgressBTN = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        StudentIDTXT = new javax.swing.JTextField();
        CourseIDTXT = new javax.swing.JTextField();
        ComponentTXT = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        RecMarkTXT = new javax.swing.JTextField();
        addProgressBTN = new javax.swing.JButton();
        updateProgressBTN = new javax.swing.JButton();
        removeProgressBTN = new javax.swing.JButton();
        searchProgressBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        progressTable = new javax.swing.JTable();
        examRBTN = new javax.swing.JRadioButton();
        assignmentRBTN = new javax.swing.JRadioButton();
        pendingRBTN = new javax.swing.JRadioButton();
        inProgRBTN = new javax.swing.JRadioButton();
        completedRBTN = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Recovery Progress");

        resetProgressBTN.setText("Reset");
        resetProgressBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetProgressBTNActionPerformed(evt);
            }
        });

        jLabel3.setText("Student ID:");

        jLabel4.setText("Course ID:");

        jLabel5.setText("Component:");

        jLabel6.setText("Progress:");

        StudentIDTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentIDTXTActionPerformed(evt);
            }
        });

        ComponentTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComponentTXTActionPerformed(evt);
            }
        });

        jLabel1.setText("Recovery Mark:");

        RecMarkTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecMarkTXTActionPerformed(evt);
            }
        });

        addProgressBTN.setText("Add");
        addProgressBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProgressBTNActionPerformed(evt);
            }
        });

        updateProgressBTN.setText("Update");
        updateProgressBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProgressBTNActionPerformed(evt);
            }
        });

        removeProgressBTN.setText("Remove");
        removeProgressBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeProgressBTNActionPerformed(evt);
            }
        });

        searchProgressBTN.setText("Search");
        searchProgressBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchProgressBTNActionPerformed(evt);
            }
        });

        progressTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "StudentID", "CourseID", "Component", "Progress", "Mark"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(progressTable);

        buttonGroup1.add(examRBTN);
        examRBTN.setText("Exam");

        buttonGroup1.add(assignmentRBTN);
        assignmentRBTN.setText("Assignment");
        assignmentRBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignmentRBTNActionPerformed(evt);
            }
        });

        buttonGroup2.add(pendingRBTN);
        pendingRBTN.setText("Pending");

        buttonGroup2.add(inProgRBTN);
        inProgRBTN.setText("In Progress");

        buttonGroup2.add(completedRBTN);
        completedRBTN.setText("Completed");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(271, 271, 271))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(265, 265, 265)
                                .addComponent(pendingRBTN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inProgRBTN))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(45, 45, 45))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))
                                        .addGap(27, 27, 27)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(StudentIDTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CourseIDTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ComponentTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(RecMarkTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(resetProgressBTN))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ProgressTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(162, 162, 162)
                                        .addComponent(completedRBTN))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(examRBTN)
                                .addGap(18, 18, 18)
                                .addComponent(assignmentRBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)))
                        .addGap(100, 100, 100))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(addProgressBTN)
                                .addGap(86, 86, 86)
                                .addComponent(updateProgressBTN)
                                .addGap(325, 325, 325))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(removeProgressBTN)
                                .addGap(65, 65, 65)
                                .addComponent(searchProgressBTN)
                                .addGap(28, 28, 28)))
                        .addGap(72, 72, 72))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StudentIDTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(resetProgressBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CourseIDTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ComponentTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(examRBTN)
                    .addComponent(assignmentRBTN))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProgressTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(pendingRBTN)
                    .addComponent(inProgRBTN)
                    .addComponent(completedRBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(RecMarkTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addProgressBTN)
                        .addComponent(removeProgressBTN)
                        .addComponent(searchProgressBTN))
                    .addComponent(updateProgressBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetProgressBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetProgressBTNActionPerformed
        List<RecoveryProgress> allRecs = manager.loadFromFile(filename);

        DefaultTableModel model = (DefaultTableModel) progressTable.getModel();
        model.setRowCount(0);

        for (RecoveryProgress rec : allRecs) {
            model.addRow(new Object[]{
                rec.getStudentID(),
                rec.getCourseID(),
                rec.getComponent(),
                rec.getProgress(),
                rec.getRecoveryMark()
            });
        }

        StudentIDTXT.setText("");
        CourseIDTXT.setText("");
        ComponentTXT.setText("");
        ProgressTXT.setText("");
        RecMarkTXT.setText("");
    }//GEN-LAST:event_resetProgressBTNActionPerformed

    private void searchProgressBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchProgressBTNActionPerformed
        String studentID = StudentIDTXT.getText();
        String courseID = CourseIDTXT.getText();
        String component = ComponentTXT.getText();
        String progress = ProgressTXT.getText();
        
        List<RecoveryProgress> results = manager.searchRecord(studentID, courseID, component, progress);   
        
        DefaultTableModel model = (DefaultTableModel) progressTable.getModel();
        model.setRowCount(0);
        
        for (RecoveryProgress rec : results) {
            model.addRow(new Object[] {
                rec.getStudentID(),
                rec.getCourseID(),
                rec.getComponent(),
                rec.getProgress(),
                rec.getRecoveryMark()
            });
        }
        
        if (results.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No matching records found.");
        }
    }//GEN-LAST:event_searchProgressBTNActionPerformed

    private void addProgressBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProgressBTNActionPerformed
        String studentID = StudentIDTXT.getText();
        String courseID = CourseIDTXT.getText();
        String component = ComponentTXT.getText();
        String progress = ProgressTXT.getText();
        String recMark = RecMarkTXT.getText();
        
        if (studentID.isEmpty() || courseID.isEmpty() || component.isEmpty() || progress.isEmpty() || recMark.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!validator.isValidStudent(studentID)) {
            JOptionPane.showMessageDialog(this, "Invalid Student ID! Please enter an existing student.");
            return;
        }
        
        if (!validator.isValidCourse(courseID)) {
            JOptionPane.showMessageDialog(this, "Invalid Course ID! Please enter an existing course.");
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to add this new Progress?",
            "Confirm Add",
            JOptionPane.YES_NO_OPTION
        );


        if (confirm == JOptionPane.YES_OPTION) {
            RecoveryProgress newRec = new RecoveryProgress(studentID, courseID, component, progress, recMark);
            manager.addRecord(filename, newRec);
            JOptionPane.showMessageDialog(this, "Progress added successfully!");
            displayProgress();
            clearFields();
        }

        //Clear input fields
        StudentIDTXT.setText("");
        CourseIDTXT.setText("");
        ComponentTXT.setText("");
        ProgressTXT.setText("");
        RecMarkTXT.setText("");
    }//GEN-LAST:event_addProgressBTNActionPerformed

    private void updateProgressBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProgressBTNActionPerformed
        int selectedRow = progressTable.getSelectedRow();
        
        if (selectedRow >= 0) {    
            String studentID = StudentIDTXT.getText();
            String courseID = CourseIDTXT.getText();
            String component = ComponentTXT.getText();
            String progress = ProgressTXT.getText();
            String recMark = RecMarkTXT.getText();
        
            if (studentID.isEmpty() || courseID.isEmpty() || component.isEmpty() || progress.isEmpty() || recMark.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please fill in all fields!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (!validator.isValidStudent(studentID)) {
                JOptionPane.showMessageDialog(this, "Invalid Student ID! Please enter an existing student.");
                return;
            }

            if (!validator.isValidCourse(courseID)) {
                JOptionPane.showMessageDialog(this, "Invalid Course ID! Please enter an existing course.");
                return;
            }
                
            int confirm = JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to update this Progress?",
                "Confirm Update",
                JOptionPane.YES_NO_OPTION
            );

            if (confirm == JOptionPane.YES_OPTION) {
                String updateData = progress + "|" + recMark;
                manager.updateRecord(filename, StudentIDTXT.getText(), CourseIDTXT.getText(), ComponentTXT.getText(), updateData    );
                JOptionPane.showMessageDialog(this, "Progress updated successfully!");
                displayProgress();
                clearFields();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a row to update.");
        }
    }//GEN-LAST:event_updateProgressBTNActionPerformed

    private void removeProgressBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeProgressBTNActionPerformed
        int selectedRow = progressTable.getSelectedRow();
        
        if (selectedRow >= 0) {
            // Get values from the selected row
            String studentID = progressTable.getValueAt(selectedRow, 0).toString();
            String courseID = progressTable.getValueAt(selectedRow, 1).toString();
            

            // Confirm deletion
            int confirm = JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to remove the progress for Student ID: " + studentID + 
                " and Course ID: " + courseID + "?",
                "Confirm Deletion",
                JOptionPane.YES_NO_OPTION
            );
            
            if (confirm == JOptionPane.YES_OPTION) {
                // Remove from file
                manager.removeRecord(filename, studentID, courseID);
                JOptionPane.showMessageDialog(this, "Progress removed successfully!");

                // Refresh table and clear text fields
                displayProgress();
                clearFields();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a row to remove.");
        }   
    }//GEN-LAST:event_removeProgressBTNActionPerformed

    private void assignmentRBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignmentRBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assignmentRBTNActionPerformed

    private void StudentIDTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentIDTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentIDTXTActionPerformed

    private void ComponentTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComponentTXTActionPerformed
 
    }//GEN-LAST:event_ComponentTXTActionPerformed

    private void RecMarkTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecMarkTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecMarkTXTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecoveryProgressForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecoveryProgressForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecoveryProgressForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecoveryProgressForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecoveryProgressForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ComponentTXT;
    private javax.swing.JTextField CourseIDTXT;
    private javax.swing.JTextField ProgressTXT;
    private javax.swing.JTextField RecMarkTXT;
    private javax.swing.JTextField StudentIDTXT;
    private javax.swing.JButton addProgressBTN;
    private javax.swing.JRadioButton assignmentRBTN;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton completedRBTN;
    private javax.swing.JRadioButton examRBTN;
    private javax.swing.JRadioButton inProgRBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton pendingRBTN;
    private javax.swing.JTable progressTable;
    private javax.swing.JButton removeProgressBTN;
    private javax.swing.JButton resetProgressBTN;
    private javax.swing.JButton searchProgressBTN;
    private javax.swing.JButton updateProgressBTN;
    // End of variables declaration//GEN-END:variables
}
